### ISSUE TITLE
Sometimes trade account disappears

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#100]
It happened after and deposited and refreshed the view

and also after I submitted an order.

Usually comes back after a refresh though.

![img_0125](https://user-images.githubusercontent.com/16552874/46387597-613c3d80-c702-11e8-9f14-f5d1d33eb910.PNG)

**Comment by creyeknife** [comment]
Oh now I have noticed that I put all the money in my trade acccount into an order and it's showing as totally empty and asking me to deposit. So I cannot see my orders or anything. 

It seems the trade account is also being weird on Android at the moment too. 

![img_0126](https://user-images.githubusercontent.com/16552874/46387732-1a027c80-c703-11e8-85e3-b964bf7828b0.PNG)

**Comment by apisit** [comment]
fixed.
