### ISSUE TITLE
Swiping between accounts on portfolio shows erratic value data.

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#117]
When swiping between accounts on the portfolio, it can take a long time for it to update the value amount and shows the amount for the last one usually. 

Sometimes if you go too fast it will load the wrong amount and then reload it again after a while.

Suggested fix: Maybe we could show a gray 0 instead of an incorrect amount. Then it will load and turn blue. The experience will just feel more solid I think.

**Comment by saltyskip** [comment]
done
