### ISSUE TITLE
Show PIN/Print dialogue on loading of app

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#118]
Not totally sure about this but want to try it. 

When the user loads the app, it shows the thumb print entry straight away.
If they enter their print it just load the current wallet.
If they hit cancel, they can select another wallet from the list and sign in to that instead.

My thinking here is that users will mostly use one wallet. They wont be changing between wallets every time they open the app. The option is there but the flow is streamlined for quick access to your everyday wallet.

**Comment by saltyskip** [comment]
done
