### ISSUE TITLE
O3 account in wallet screen takes a long time to load values

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#126]
I seem to get a lot of lag sometimes when trying to load the value of the O3 account on the wallet page. 

It also seems to sometimes load incorrect amounts. Showing only half my tokens etc. Then updating after a while. 

Could use some performance enhancements and checks to make sure it's displaying correctly.
If there is a bigger issue, maybe we can look at adding a loader or something till it can be fixed.

**Comment by saltyskip** [comment]
Needs more investigation

**Comment by saltyskip** [comment]
I think it will be improved now, let me know
