### ISSUE TITLE
NNS section

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#127]
Need a new icon for button 
New label
Fix up layout of bottom sheet to be more consistent with other ones. 
Loader animation while it's resolving the names

With this said, I am still a bit unsure of the reason for this view. Besides being able to see a list of NNS names attached to your wallet, it doesn't do much. Once you click on and it opens the page, there isn'y much you can do there either besides taking a screen shot. 

The other issue I have is the fact that the names don't necessarily go to that address. It can be mapped elsewhere. Think we need to be careful about this. 

Need to work on this more I think to consider the actual use case for this etc. Probably needs more alignement with the identity stuff. But we should at least make it useful enough to get it over the line for the next release. and then we can improve later.

**Comment by saltyskip** [comment]
Will link as bottom sheet right now just to display names.
