### ISSUE TITLE
ONG claiming error states

### ISSUE THREAD

**Issue by Arco91** [O3Labs/OzoneWalletIOS#144]
Unlike Android/Desktop, it will let users sync even if the claimable amount is <0.02
I think we need to stop users from claiming here as it is costing more than they will receive.

Also after sync state, if user has claimable ONG but no ONG to pay the fee with and they click claim then it still shows success even though it didn't succeed.

Can we make it the same as on desktop, and block the user completely from pushing the claim button like on desktop with an error message like this?
![screenshot 2018-11-14 at 16 37 57](https://user-images.githubusercontent.com/38653228/48468195-89a17680-e82e-11e8-8f76-069ddf68fa98.png)

**Comment by saltyskip** [comment]
done
