### ISSUE TITLE
Empty secondary wallets don't show add tokens empty state

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#150]
When you add a secondary wallet, and it has no tokens, it just shows empty graphy instead of the 'you have no tokens, add some now" state.

Would be good for consistency to show it here.

**Comment by saltyskip** [comment]
I don't think we want to do this, mainly because of the confusion it causes between watch addresses and secondary wallets.

**Comment by creyeknife** [comment]
ah yer that makes sense.
