### ISSUE TITLE
Verify backup dark mode

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#162]
On the verify back up view:
Left align text
Bold the checkbox titles
Remove the blank space under the buttons
Add . at the end of description
Update text to read:
"You can manually back up your wallet by taking a screen shot of the QR key or copying down the text key. Please be sure it is saved in a very safe place. If you lose your key, your funds cannot be recovered." 

Also:
There is no dark mode theme for verify backup

![img_0164](https://user-images.githubusercontent.com/16552874/50954711-865afc00-14fa-11e9-80d0-fad048b9a23a.PNG)

**Comment by saltyskip** [comment]
done
