### ISSUE TITLE
Layout for Verify Backup bottom sheet

### ISSUE THREAD

**Issue by AGKDesigns** [O3Labs/OzoneWalletIOS#164]
Left align description text

Update text to: 
You can manually back up your wallet by taking a screen shot of the QR key or copying down the text key. Please be sure it is saved in a very safe place. If you lose your key, your funds cannot be recovered.

Bold the titles on the checkboxes

Remove the button space 

<img width="508" alt="screen shot 2019-01-10 at 5 23 21 pm" src="https://user-images.githubusercontent.com/16552874/50955427-73492b80-14fc-11e9-9f7e-e58767bf22a0.png">

**Comment by saltyskip** [comment]
THis is the min height that will fit on iphone SE ;)

**Comment by creyeknife** [comment]
iPhone doesn’t support resizing windows dependent on device?

**Comment by saltyskip** [comment]
Unfortunately no, you'll see all bottom sheets we have in ios are actually same size

**Comment by creyeknife** [comment]
wow…. iPhone….. is rubbish
