### ISSUE TITLE
Forced security update text and animation

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#173]
New key animation : https://drive.google.com/open?id=1OKPmEC0aGv1YJvADgvHIa5k_AKNQFPtW

Text:
Title: O3 security update
Desc:
O3 has recently improved its security and added multiple wallet functionality. To continue using the app, all wallets now require a safer encrypted private key with a passphrase.

Please enter a passphrase for your wallet. 

[Enter passphrase]
[verify passphrase]

This passphrase will be used to encrypt your private key.

{Generate Encrypted Key}

**Comment by saltyskip** [comment]
close
