### ISSUE TITLE
Screen freezes after recovering app from iCloud

### ISSUE THREAD

**Issue by Arco91** [O3Labs/OzoneWalletIOS#181]
After restoring the app from iCloud (like when user has a new phone and restores from backup of previous phone), the screen is stuck on the select wallet screen. 

Only way to solve it right now is to have users delete and then reinstall the app but users don't know about this.

I think it has to do with the fact that the private key is not on the device yet but it should show some error or instead it should just be completely empty and give the option to create a new wallet or login with existing wallet.

**Comment by saltyskip** [comment]
Fixed
