### ISSUE TITLE
Price truncating on Token price history view

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#64]
When the app is set to yen, and you click on a token to view it's price history, it truncates the price were the decimal place would normal be for dollars etc.

The example below should read ¥657. not ¥6

![img_0066](https://user-images.githubusercontent.com/16552874/41523422-eb66af5a-7314-11e8-9555-9a4d649009f8.PNG)

**Comment by saltyskip** [comment]
done
