### ISSUE TITLE
Adding an address that has already been added

### ISSUE THREAD

**Issue by creyeknife** [O3Labs/OzoneWalletIOS#87]
When you add an address that is already added, it goes to the screen and puts the name of the added address in the address field.

![img_0118](https://user-images.githubusercontent.com/16552874/44381729-a6d6e980-a54c-11e8-9486-33ec5b08189c.PNG)

It would be cool if it showed the already added address/nickname and allowed you to edit/update the nickname.

Maybe the label is changed to edit contact or something.

**Comment by creyeknife** [comment]
Use a pre-entered title like Claim or Mint. Something that is not actually in your address book.

**Comment by apisit** [comment]
oh i see. let me get rid of them both. thanks

**Comment by apisit** [comment]
done
